name: 國家寶藏
name_en: Taiwan National Treasure

description: 關於台灣過去的拼圖，散落在全世界的各個角落。我們需要把它們找出來、加以數位化，轉譯成為人人都可取用的開放資料與有意義的歷史故事。國家寶藏號召志工一起深入世界各地的國家檔案局與圖書館，挖出台灣相關史料，並建立網路開放資料庫，供全民免費使用。
description_en: 

abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/nationaltreasure/2020/twnationaltreasure_00.jpg
header_image: 
avatar_image: 
theme_color: 

start: 
end: 

type_ids:
  - community
topic_ids:
  - data
field_ids:
  - art
tags:
tags_en:

metas:
metas_en:

links:
  - title: 贊助社群
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=35
links_en:

actions:
actions_en:

advisor_ids:
organizer_ids:
  - nationaltreasure
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
  - pofeng
staff_ids:
  - rosa

listed: yes
listed_en: 

reports:
reports_en:
