name: 110 年客家開放資料推廣及活化
name_en: Hakka x OpenData 

description: 透過引導客家社群使用數位工具，將族群文化與在地知識轉譯為數位資訊，我們進一步促進集體認同的凝聚。讓客家社群內不同世代有了交流，並朝發展出與其他文化群體互動交流的機制之方向前進。
description_en: 

tagline: 以開放資料推廣客家文化
tagline_en: 

og_image: /p/hakka/illustration_1.png
header_image: 
avatar_image: 
theme_color: blue

start: 
end: 

topic_ids:
  - infosec
field_ids:
  - it
tags:
tags_en:

organizer_ids:
  - hpcf
co-organizer_ids:
  - ocf
  - wikiTW

consultant_ids:
  - hpcf

board_ids:
  - pofeng
staff_ids:
  - weichen

listed: yes
listed_en: yes

reports:
