name: 110 年客家開放資料推廣及活化
name_en: Hakka x OpenData 

description: 以開放資料推廣客家文化。
description_en: 

tagline: 
tagline_en: 

og_image: /p/hakka/illustration_1.png
header_image: /p/hakka/banner_1.png
avatar_image: 
theme_color: grey

start: 
end: 

topic_ids:
  - data
field_ids:
  - it
tags:
tags_en:

organizer_ids:
  - hpcf
co-organizer_ids:
  - ocf
  - wikimediatw

consultant_ids:
  - hpcf

board_ids:
  - 
staff_ids:
  - 

listed: yes
listed_en: yes

reports:
