
name: 開源貢獻者快速通關
name_en: OSCVPass

description: 「開源者貢獻票」是在台灣開源社群大型活動中常見的優惠票券，只要向活動主辦方提交在開源領域各個專案的特殊貢獻，即可申請獲取。但參與不同活動往往得分次申請，除了麻煩還是麻煩。<br>為了免去繁瑣程序，OCF 啟動 全新 OSCVPass (開源貢獻者快速通關)專案，僅需向 OCF 提交一次資料，即可申請 COSCUP、SITCON、MOPCON 開源貢獻票！<br\><br>想優惠入坑又不用費時費力？<br\><br>馬上加入 OSCVPass，開啟快速通關新世界！<br\>
description_en: OSCVPass is a quick solution for open-source contributors to attend Taiwan's open-source events：COSCUP, SITCON, MOPCON by a one-time application form.
abbr: 
abbr_en: 

tagline: 省時快速、輕鬆開源！
tagline_en: 

og_image: /p/oscvpass/2019/OSCVPASS_Banner.png
header_image: /p/oscvpass/2019/OSCVPASS_city.png
avatar_image: /p/oscvpass/2019/OSCVPASS_Banner.png
theme_color: yellow

start: 
end: 


topic_ids:
  - misc
field_ids:
  - community
tags:
tags_en:

metas:
metas_en:

links:
links_en:

actions:
  - title: 馬上填寫表單
    url: https://forms.gle/j62bUmTy1hKKGm7n6
    color: pink
    icon: pencil alternate
  - title: 贊助OCF專案
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=7
    color: green
    icon: dollar sign
actions_en:

advisor_ids:
organizer_ids:
  - ocf
  - coscup
  - sitcon
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
staff_ids:
  - singing
  - rosa

listed: yes
listed_en: yes

reports:
reports_en:
