name: 議題關注
name_en: Law and policy issues

description: 與社會與開放科技息息相關的各項議題，如果還少了那份關注力道，OCF 期許自己加入推動行列! 
description_en: Lots of public policies have open-source technical issues hidden inside. We focus on those issues, check related law and policy, try to find out if there's any problem, or make initializing laws and policies, or advocating corrections.
  
abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/issues/issues-og.png
header_image: /p/issues/issues-cover.png
avatar_image: /p/issues/issues-og.png
theme_color: 

start: 
end: 

type_ids:
topic_ids:
field_ids:
tags:
tags_en:

metas:
  - label: 
    content: 
metas_en:

links:
  - title: 網路自由小聚
    url: https://ocf.tw/p/issues/2021/coffeeandcircumvention.html
    icon:
  - title: eID 數位身分證
    url: https://ocf.tw/p/eid/
    icon: 
  - title: 開放資料專法推動
    url: https://lab.ocf.tw/2020/03/12/opendatanextstep/
    icon: 
  - title: OGP 開放政府國家行動方案推動
    url: https://lab.ocf.tw/2021/08/04/twogp/
    icon:
  - title: 5G 開放原始碼與資安主題分享
    url: https://ocf.tw/p/issues/2020/5G.html
    icon:

links_en:
  - title: Internet Freedom meetup
    url: https://ocf.tw/en/p/issues/coffeeandcircumventionen.html
    icon: 
  - title: eID
    url: https://ocf.tw/en/p/eid/
    icon: 
  - title: Open Data initiative
    url: https://lab.ocf.tw/2020/03/18/opendatanext-eng/
    icon: 
  - title: Open Government
    url: https://opengovreport.ocf.tw/#tab-0
    icon: 
  - title: Open Source and Security for 5G
    url: https://ocf.tw/p/issues/2020/5G.html
    icon:


actions:
  - title: 捐款支持
    url: http://ocf.tw/300
    icon: dollar
    color: green
  - title: 
actions_en:

advisor_ids:
organizer_ids:
  - ocf
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
staff_ids:

listed: yes
listed_en: yes

reports:
  yyyy: mm


