
name: 開源教
name_en: The Openists

description: 開源教 (The Openists) 是開放文化基金會所草創的非宗教活動，主旨在活絡開源社群精神，持續地開放共享和自主學習，歡迎開源教友們一起來分享和學習！有想分享的主題也歡迎聯絡我們！
description_en: 
abbr: 
abbr_en: 

tagline: 教你開放文化的那些事
tagline_en: 

og_image: /p/openists/openists-og.png
header_image: /p/openists/openists-cover.png
avatar_image: /p/openists/openists-avatar.png
theme_color: 

start: 
end: 


topic_ids:
  - misc
field_ids:
  - education
tags:
tags_en:

actions:
  - title: 支持更多活動
    url: https://ocf.tw/300
    color: blue
    icon: 
actions_en:
links:
  - title: 錄影檔案
    url: https://www.youtube.com/playlist?list=PLFuYOsppHDrnkhreO8LEfKwclaSAmKvf-
  - title: 簡報集中區
    url: https://drive.google.com/drive/folders/1SrYPdIYyOF0kBEkIetuIf82L1u6PceWv
advisor_ids:
organizer_ids:
  - ocf

co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:

donors:
donors_en:

board_ids:
  - pofeng

staff_ids:
  - rock

listed: yes
listed_en: 

reports:
reports_en:
