name: 台灣開源法律網絡
name_en: Open Source Legal Network

description: 開放授權 (Open License)，是跨界團結眾多參與人士的運作規則，然而，有時因為解讀立場不同，導致近年紛爭日起。因應於此，「台灣開源法律網絡（Open Source Legal Network, Taiwan）」，是希望在國內建立一個中立客觀且保障參與隱私的自由開源法律資訊分享網絡。
description_en: 
abbr: OSLN.TW
abbr_en: OSLN.TW

tagline: OSLN.TW
tagline_en: 

og_image: /p/osln/2019/og.png
header_image: /p/osln/2019/og.png
avatar_image: /p/osln/2019/avatar.png
theme_color: 

start: 
end: 

type_ids:
  - community
topic_ids:
  - source
field_ids:
  - legal
tags:
  - 定期活動
tags_en:


actions: 
  - title: 贊助專案
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=21
    color: green
    icon: dollar
    
organizer_ids:
  - osln
co-organizer_ids:
  - ocf
coordinator_id:
  - lucien
board_ids:
  - pofeng
staff_ids: 
  - rock

listed: yes
listed_en: 
