name: 專案名人堂
name_en: Legends (CLOSED Proejcts)

description: 這些專案已經結束啦！過去累積一篇又一篇的討論和想法，都是我們推動社會的正向力量，每個專案都有許多的主題與能量，歡迎來看看！雖然我們未來不再更新他們，但裡面的內容能讓我們一起分享和自主學習！

description_en: 
og_image: /p/legends/legends-og.png
header_image: /p/legends/legends-og.png
avatar_image: /p/legends/legends-og.png
theme_color: teal

start: 
end: 


topic_ids:
field_ids:

links: 
  - title: OCF Lab - 開放與科技的新知匯集
    url: https://lab.ocf.tw/
  - title: 開源教 - 一個讓開源人分享學習的舞台
    url: https://ocf.tw/p/openists/
  - title: PTT ID Profiling - 用開源的方式側寫那些怪怪的 PTT 帳號
    url: https://ocf.tw/p/pttid/

links_en: 
  - title: The Openists playlist (YouTube)
    url: https://www.youtube.com/playlist?list=PLFuYOsppHDrnkhreO8LEfKwclaSAmKvf-
  - title: The Openists slides download
    url: https://drive.google.com/drive/folders/1SrYPdIYyOF0kBEkIetuIf82L1u6PceWv
  - title: PTT ID Profiling crawler
    url: https://github.com/ocftw/PttCrawler
  - title: PTT ID Profiling analyzing tool
    url: https://github.com/ocftw/anomaly_detection_in_PTT_forum
  - title: PTT ID Profiling report (CC BY-SA 4.0)
    url: https://drive.google.com/open?id=1FGB-kbNtRz11FU__0nomJioB146qw2fW
  - title: PTT ID Profiling raw data（The data is public access and downloaded from PTT public forum, if you wish to remove the data that contains your personal speech, please contact us.)
    url: https://drive.google.com/open?id=1GvxUiD4LLU8xyXVkzXsxB_4MGJ1x2b3K


organizer_ids:
  - ocf
sponsor_ids:

coordinator_ids:

board_ids: 
staff_ids: 
listed: yes
listed_en: yes
