name: 網路自由小聚
name_en: Coffee & Circumvention @Taipei 

description: 在國際夥伴 Internet Freedom Festival 社群的建議之下，OCF 和來自「摩茲台灣社群Mozilla TW」、 「COSCUP」、和「公民團體資安暨隱私交流 CSCS (Cyber Shield Civil Society)」的夥伴一起發起了每月固定的網路自由小聚。從 2019 年 9 月開始，我們固定每個月第三個禮拜四晚上，在摩茲工寮聚會，至今只有一次因為春節暫停。而本來實驗性質的小聚，意外地不斷茁壯，每次聚會都有固定參與者、新參與者，也有更多夥伴加入籌辦和討論主題發想。為什麼要來網路自由小聚? 身在台灣的我們，或許對於網路自由反而比較無感，因為跟世界上許多地方相比，台灣的網路世界相對自由、較沒受到監控、管制和侵害，因此沒有深刻感受到國際上疾呼且捍衛網路自由的結迫性。 然而，現代數位社會，一言一行早已跨越國界，人人都應該要關心自身在數位世界上的權利。大家一起來小聚聊聊，認識更多全球重要網路自由課題!!!!!!
description_en: This is a monthly meetup which focuses on talking about internet freedom. The idea of the meetup came from the Internet Freedom Festival (IFF), one of the largest digital rights communities in the world. It gathers hackers from all over the world to defend activists oin the frontline. OCF was invited by IFF to initiate  “Coffee & Circumvention” (C&C) in Taiwan. The C&C meetup was planned to be hosted in many cities across in the world by local groups to discuss the issues regarding internet freedom and digital rights on every 3rd Thursday in the month. The meetup now is localized in Taiwan and called  ”Internet Freedom Meetup 網路自由小聚“ The first Internet Freedom Meetup was held in September. 2019 by OCF and partners from Mozilla TW, COSCUP (conference for open source), and CSCS (Cyber Shield Civil Society).  In the beginning, we viewed this Meetup as athe test because not many people talked about internet freedom in Taiwan, even within technology communities.  However, surprisingly, people regularly attend the meetup and we always have new comers. Now, the meetup has athe growing organizers’ group, several attendees volunteered to be the organizers and bring their ideas and knowledge into the meetup.Because our internet is more open,  less monitored, and has less control and threats than in many other part of the world, a lot of us in Taiwan might not feel very engaged with the concept of internet freedom, and thus many aren’t aware of the urgency of standing up for and defending internet freedom internationally. In the digital age, everything written online travels beyond borders, and everyone needs to be aware of their digital rights So let’s get together and chat and get to understand important aspects of global internet freedom The note of each meetup https://hackmd.io/75rmGtgfRe2UhKCYpIRc3Q 

abbr: 網路自由小聚
abbr_en: Coffee & Circumvention @Taipei 

tagline: Conference for Open Source Coders, Users and Promoters
tagline_en: Conference for Open Source Coders, Users and Promoters

og_image: 
header_image: 
avatar_image: 
theme_color: 

start: 
end: 

type_ids:
topic_ids:
field_ids:
tags:
tags_en:

metas:
  - label: 
    content: 
metas_en:

links:
  - title: 
    url: 
    icon: 
links_en:

actions:
  - title: 
    url: 
    icon: 
    color: 
  - title: 
actions_en:

advisor_ids:
organizer_ids: 
  - ocf
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
staff_ids:

listed: yes
listed_en: yes 

reports:
  yyyy: 
