name: Cofacts 真的假的
name_en: Cofacts

description: 2016 發起的 Cofacts 真的假的 是針對假新聞與不實資訊最早也唯一開源的公民協作事實查核聊天機器人專案。由青年志工與程式開發者發起，每兩個月舉辦一次編輯技巧實作聚會與不定時媒體識讀講座。透過資訊科技與技術交流，鼓勵公民參與與堅持言論自由，防止詐騙與花錢傷身的健康偏方傷害家人，真的假的幫助所有人一起正面迎擊不實訊息。
description_en: Founded in 2016, Cofacts is the first fact-checking chatbot and open-sourced, collaborative civic tech project combating misinformation in closed messaging apps. Comprised of volunteers and software developers, we have conducted media literacy lessons and fact-checking training workshop regularly. Cofacts has encouraged civic collaborating and valued freedom of speech, establishing an innovative and effective method countering misinformation, propaganda and fraud via collaborative fact-checking and open source technique toolkit. Cofacts achievement and experience could be replicated to another country for international collaborating.

abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/cofacts/logo.png
header_image: /p/cofacts/cover.png
avatar_image: 
theme_color: 

start: 
end: 


topic_ids:
  - data
field_ids:
  - it
tags:
tags_en:

metas:
metas_en:

links:
  - title: 成果報告
    url: https://cofacts.tw/impact
    icon: file outline
  - title: 官網
    url: https://cofacts.tw/
    icon: home
  - title: Fanpage
    url: https://www.facebook.com/cofacts.tw
    icon: facebook square

links_en: 
  - title: Impact
    url: https://cofacts.tw/impact
    icon: file outline
  - title: Website
    url: https://cofacts.tw/
    icon: home
  - title: Fanpage
    url: https://www.facebook.com/cofacts.tw
    icon: facebook square

actions:
  - title: 加入好友
    url: https://lin.ee/gZ4CCc0
    icon: address book outline
  - title: 募款專頁
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=48
    icon: money
  - title: Facebook Group
    url: https://www.facebook.com/groups/cofacts
    icon: facebook
  - title: Github
    url: https://github.com/cofacts
    icon: github
actions_en:
  - title: Chatbot
    url: https://lin.ee/gZ4CCc0
    icon: address book outline
  - title: Donate
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=48
    icon: money
  - title: Facebook Group
    url: https://www.facebook.com/groups/cofacts
    icon: facebook
  - title: Github
    url: https://github.com/cofacts
    icon: github

advisor_ids:
organizer_ids:
  - cofacts
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
  - clkao
staff_ids:
  - rock

listed: yes
listed_en: yes

reports:
