name: Ruby Taiwan
name_en: Ruby Taiwan

description: Ruby Taiwan 社群成立於 2008 年 10 月，主要針對 Ruby 程式語言及軟體開發，舉辦各式講座活動與國際研討會等各式活動，提昇開發人員的技術深度與廣度，增進業界的分享交流，目前舉辦的活動有：Taipei.rb, RubyConf Taiwan, Rails Girls 等。
description_en: 

tagline: 
tagline_en: 

og_image: /p/rubytw/rubytw-logo.png
header_image: 
avatar_image: 
theme_color: blue

start: 
end: 

topic_ids:
  - rubytw
field_ids:
  - source
tags:
tags_en:

actions:
  - title: Ruby Taiwan 網站
    url: https://ruby.tw/
    color: yellow
    icon: global
  - title: Ruby Taiwan Facebook
    url: https://www.facebook.com/ruby.taiwan/
    color: green
    icon: facebook


organizer_ids:
  - rubytw
co-organizer_ids:

consultant_ids:

board_ids:
staff_ids:
  - rock

listed: yes
listed_en: 

reports:
