name: 開源星手村
name_en: Open StarTer Village 
 

description: 「開源是開放軟體嗎？我不會寫程式能做嗎？」常聽到這樣的疑問，但其實每種開源專案需要的都不只是單一種人才，開源文化也不只是軟體，而是一種精神。這款桌遊的誕生，就是希望能透過沉浸式學習，讓更多人了解什麼是開放文化的精神，未來一起做出更多酷酷的專案（⁎⁍̴̛ᴗ⁍̴̛⁎）
description_en: 


tagline: 一款給所有人的開源桌遊
tagline_en: 

og_image: /p/openstarter/cover.png
og_image_en: /p/openstarter/cover.png
header_image: /p/openstarter/banner.png
avatar_image: /p/openstarter/cover.png
theme_color: gold

start: 
end: 

topic_ids:
  - 
field_ids:
  - 
tags: 
tags_en:

links:
  - title: 開源星手村 官方網站
    url: https://sites.google.com/ocf.tw/openstarter/home
    color: green
    icon: world icon
  - title: 開源星手村 Discord
    url: https://discord.com/channels/920674931438669874/
    color: green
    icon: discord icon

links_en:
  - title: Open StarTer Village website
    url: https://sites.google.com/ocf.tw/openstarter/home
    color: green
    icon: world icon
  - title: Open StarTer Village Discord
    url: https://discord.com/channels/920674931438669874/
    color: green
    icon: discord icon

organizer_ids:
  - ocf
co-organizer_ids: 
consultant_ids: 

board_ids:

staff_ids:
  - rosa
  - claire
  - xini
  - 東東

listed: yes
listed_en: yes
