name: 國際夥伴 & 合作
name_en: Global Partnership & Collaboration 


description: 在無國界的開源社群中，與全球串聯彼此交流，並且把台灣經驗帶往國際舞台產生更大的影響力，有效串連資源，與全球開放科技社群一同成長。過去幾年，透過國際會議出訪、國際社群網絡參與、資料及經驗分享、活動舉辦，開放文化基金會積極建立國際社群 & 台灣社群的合作交流。
description_en: 

og_image: /p/global/global-og.png
header_image: /p/global/global-cover.png
avatar_image: /p/global/global-og.png

theme_color: teal

start: 
end: 

type_ids:
  - overseas
topic_ids:
  - data
field_ids:
  - it

actions: 
  - title: 捐款支持
    url: http://ocf.tw/300
    color: green
    icon: dollar

links:
  - title: OCF國際組織交流名冊
    url: 
  - title: 2016-2019 國際出訪一覽表
    url: https://hackmd.io/xUpkC7ukRA28YtsKZUj1Ug
  - title: 2014-2016台灣開放政府觀察報告
    url: https://opengovreport.ocf.tw
  - title: CivicTechFest 2017 公民科技週
    url: http://civictechfest.org/

organizer_ids:
  - ocf
sponsor_ids:

coordinator_ids:

board_ids: 
staff_ids: 
listed: yes
listed_en: 
