name: 國際夥伴 & 合作
name_en: Global Partnership & Collaboration 

description: 在無國界的開源社群中，與全球串聯彼此交流，並且把台灣經驗帶往國際舞台產生更大的影響力，有效串連資源，與全球開放科技社群一同成長。過去幾年，透過國際會議參與、跨國講座及工作坊在台舉辦、資料建置撰寫，國際交流組已與許多不同國家團體開啟實質合作的計畫，建立緊密的全球夥伴網絡。
description_en: OCF always trying to connect with those who are interested in open source, bring Taiwan experience to the world, and grow with the global community. In the past few years, through international conferences, workshops, data construction, and information sharing, our International Networking Program has teamed up with other organizations, launched many collaborative projects, and created a tight network with open & tech communities from all over the world.
og_image: /p/pttid/pttid-og.png
header_image: /p/pttid/pttid-cover.png
avatar_image: /p/pttid/pttid-og.png
theme_color: teal

start: 
end: 

type_ids:
  - overseas
topic_ids:
  - data
field_ids:
  - it

actions: 
  - title: 捐款支持
    url: http://ocf.tw/300
    color: green
    icon: dollar

links:
  - title: 爬蟲工具
    url: https://github.com/ocftw/PttCrawler
  - title: 分析工具
    url: https://github.com/ocftw/anomaly_detection_in_PTT_forum
  - title: 工具教學 (擱置中，歡迎捐款支持！)
    url:
  - title: 分析報告 (CC BY-SA 4.0)
    url: https://drive.google.com/open?id=1FGB-kbNtRz11FU__0nomJioB146qw2fW
  - title: 原始分析資料檔案（本資料爬取自 PTT 網站，皆為網路上公開的資料，如果您希望移除個人發言資訊，請 Email 聯絡我們）
    url: https://drive.google.com/open?id=1GvxUiD4LLU8xyXVkzXsxB_4MGJ1x2b3K
organizer_ids:
  - ocf
sponsor_ids:

coordinator_ids:

board_ids: 
staff_ids: 
listed: 
listed_en: 
