name: 系統軟體走向國際
name_en: System Program Incubation

description: 從參與時間較長、自學能力佳的學生族群著手，帶領不同學校、不同科系、不同年齡的學生，給予其足夠的資源，透過開放原始碼專案的參與，爭取國際交流的機會，從而和個別領域的一流高手交流，最終再讓這些資源回到台灣這塊土地。
description_en: 

abbr: 
abbr_en: 

tagline: 資助學生參與國際研討會、添購實驗用硬體耗材、邀請旅外業界講師
tagline_en: 

og_image: /p/sysprogram/2016/logo.png
header_image: /p/sysprogram/2017/slogan.png
avatar_image: /p/sysprogram/2016/logo.png
theme_color: blue

start: 
end: 


topic_ids:
  - source
field_ids:
  - it
tags:
tags_en:

metas:
metas_en:

links:
links_en:

actions:
  - title: 贊助專案
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=27
    color: green
    icon: dollar
  - title: 如果你想捐贈我們正需要的教材、儀器設備，請與我們聯絡 ( hi at ocf.tw)。
actions_en:

advisor_ids:
organizer_ids:
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
  - jserv
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
  - pofeng
staff_ids:
  - singing

listed: yes
listed_en: 

reports:
reports_en:
