name: openSUSE Taiwan
name_en: openSUSE Taiwan

description: openSUSE 是基於 Linux 的開源作業系統，適合初學者、有經驗的使用者以及超級技客。正體中文社群創立於 2011 年，協助翻譯 Release notes 與 Wiki 條目、舉辦 Release Party 與 InstallFest 等活動。
description_en: 

abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/opensuse/2016/og.png
header_image: 
avatar_image: 
theme_color: 

start: 
end: 


topic_ids:
  - source
field_ids:
  - it
tags:
tags_en:

metas:
metas_en:

links:
  - title: 贊助社群
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=17
  - title: 官方網站
    url: https://zh-tw.opensuse.org
  - title: 參加聚會
    url: http://opensuse-tw.kktix.cc/
links_en:

actions:
actions_en:

advisor_ids:
organizer_ids:
  - opensuse
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
staff_ids:
  - rock

listed: yes
listed_en: 

reports:
