name: OCF Lab
name_en: OCF Lab

description: 藉由一次又一次 Lab 裡的小實驗，累積一篇又一篇的討論和想法，讓開源、開放的數位科技成為推動社會的正向力量！
description_en: OCF Lab is an information platform focused on the issues of open technology, including open source, open data, open government and digital rights and internet freedom. OCF Lab intends to make these issues more close to the public and bring the positive force of the technology to the society.
og_image: /p/ocflab/ocflab-og.png
header_image: /p/ocflab/ocflab-cover.png
avatar_image: /p/ocflab/ocflab-og.png
theme_color: teal

start: 
end: 


topic_ids:
  - data
field_ids:
  - media

links: 
  - title: OCF Lab 網站
    url: https://lab.ocf.tw/

links_en:
  - title: OCF Lab
    url: https://lab.ocf.tw/

organizer_ids:
  - ocf
sponsor_ids:

coordinator_ids:

board_ids: 
staff_ids: 
listed: yes
listed_en: yes
