name: 伴伴學 Accomdemy - 陪伴科技學習
name_en: Accomdemy

description: 伴伴學 Accomdemy 是由一群來自科技、新創與教育等不同領域的夥伴們所發起的自學社群。
description_en: 

abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/accomdemy/acclogo.png
header_image: /p/accomdemy/accheader.png
avatar_image: /p/accomdemy/acclogo.png
theme_color: 

start: 
end: 


topic_ids:
  - hardware
field_ids:
  - education
tags:
tags_en:

metas:
metas_en:

links:
  - title: 伴伴學網站
    url: https://www.accomdemy.org/
    icon: home
    color: grey
  - title: 伴伴學 FB 社團
    url: https://pse.is/3wp2us
    icon: facebook
    color: grey
  - title: 伴伴學 Discord
    url: https://discord.gg/azQUs8Y2fY
    icon: comments
    color: grey
  - title: HackMD共筆
    url: https://pse.is/3ut9y8
    icon: cloud
    color: grey
  - title: 伴伴學 Youtube
    url: https://pse.is/3xx37u
    icon: file video
    color: grey
  - title: 伴學報訂閱
    url: https://pse.is/3xfc3c
    icon: cloud
    color: grey


links_en:

actions:
  - title: 2021 年伴伴學活動紀錄
    url: https://hackmd.io/JGvJSwF1RdaCKgJ8FkF7jw
    icon: microphone
    color: grey
  - title: 捐款支持伴伴學
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=52
    icon: users
    color: grey
actions_en:

advisor_ids:
organizer_ids:
  - accomdemy
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
  - honki
staff_ids:
  - rock

listed: yes
listed_en: 

reports:
