name: Java Community Conference Taiwan
name_en: Java Community Conference Taiwan

description: Java Community Conference Taiwan 是由社群主辦的 Java 開發者年會，以提供更多機會讓開發人員之間能夠互相交流。分享內容的程度不論初階到進階，只要和 Java 程式語言、框架、JVM 及虛擬化相關技術、移動裝置、開發工具、開發流程...等等，任何你認為可以分享的主題都歡迎您的投稿，歡迎分享你的發現、研究或各種實際案例經驗給大家。 
description_en: 

abbr: JCConf Taiwan
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/JCConf/2019/JCConf2019.png
header_image: 
avatar_image: 
theme_color: 

start: 2019/10/04
end: 2019/10/04

type_ids:
  - community
topic_ids:
  - source
field_ids:
  - it
tags:
  - language
  - 定期活動
  - 大型活動
tags_en:

metas:
  - label: 
    content: 
metas_en:

links:
links_en:

actions:
  - title: 
    url: 
    icon: 
    color: 
  - title: 
actions_en:

advisor_ids:
organizer_ids:
  - jcconf
co-organizer_ids:
  - ocf
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
  - pofeng
staff_ids:
  - rock
  - singing
  - rosa

listed: yes
listed_en: 

reports:
  2019: 10
reports_en:
