name: MOPCON
name_en: 

description: 
description_en: 

abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: 
header_image: 
avatar_image: 
theme_color: 

start: 
end: 

type_ids:
topic_ids:
field_ids:
tags:
tags_en:

metas:
  - label: 
    content: 
metas_en:

links:
  - title: 
    url: 
    icon: 
links_en:

actions:
  - title: 
    url: 
    icon: 
    color: 
  - title: 
actions_en:

advisor_ids:
organizer_ids:
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
staff_ids:

listed: 
listed_en: 

reports:
  yyyy: mm
reports_en:

