
name: g0v 公民科技創新獎助金
name_en: G0V Grants

description: 每一個公民科技好點子背後的創意與力量，都像是一隻輕拍翅膀的蝴蝶，若能導入持續開發、長期營運的人力與資源，就能引發蝴蝶效應，產生足以扭轉未來的成果。
description_en: The creative power of each great idea is like a flapping butterfly. With enough resources, these ideas can create positive butterfly effects and change the future. 

abbr: 
abbr_en: 

tagline: 公民科技創新獎助金，為引發正向蝴蝶效應而生！
tagline_en: g0v Civic Tech Grants, for the positive butterfly effect!

og_image: /p/g0vgrants/banner.jpg
header_image: /p/g0vgrants/banner.jpg
avatar_image: /p/g0vgrants/g0vgrant-logo.svg
theme_color: 

start: 
end: 

type_ids:
  - community
topic_ids:
  - government
field_ids:
  - it
tags:
tags_en:

metas:
  - label: 合作伙伴
    content: 2017：聯合報系願景工程、台灣大哥大基金會、前政委 蔡玉玲 律師、Openfind、天氣風險管理開發
        2018：聯合報系願景工程、中華電信、AppWorks、悠遊卡公司 
metas_en:

actions:
  - title: 獎助金成果
    url: https://grants.g0v.tw/power/
    color: green
    icon: 
  - title: 月戰報
    url: https://beta.hackfoldr.org/ctgrant-reports/
    color: blue
    icon: 
actions_en:

advisor_ids:
organizer_ids:
  - g0vjothon

co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
  - ipa

donors:
donors_en:

board_ids:
  - clkao

staff_ids:

reports:
  yyyy: mm
reports_en:

listed: yes

